name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build orders-service
        working-directory: ./orders-service
        run: mvn -B clean verify

      - name: Build tracking-service
        working-directory: ./tracking-service
        run: mvn -B clean verify

      - name: Build notification-service
        working-directory: ./notification-service
        run: mvn -B clean verify
